# Generated by Django 5.0.6 on 2024-05-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('department_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
                ('section_capacity', models.IntegerField()),
                ('section_semester', models.CharField(max_length=50)),
                ('section_year', models.IntegerField()),
                ('section_course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=200)),
                ('course_semester', models.IntegerField()),
                ('course_year', models.IntegerField()),
                ('course_credit_hours', models.IntegerField()),
                ('course_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('student_semester', models.IntegerField()),
                ('student_year', models.IntegerField()),
                ('student_phone', models.CharField(max_length=50)),
                ('student_description', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.section')),
                ('student_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.department')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_office', models.CharField(max_length=50)),
                ('teacher_phone', models.CharField(max_length=50)),
                ('teacher_description', models.CharField(max_length=200)),
                ('teacher_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.department')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='section_instructor',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Auth.teacher'),
        ),
    ]
