# Generated by Django 5.0.6 on 2024-05-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_credit_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_year',
        ),
    ]
