# Generated by Django 5.0.6 on 2024-05-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_course_course_credit_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_year',
        ),
    ]
