# Generated by Django 5.0.6 on 2024-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_section_section_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
