# Generated by Django 5.0.6 on 2024-05-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_student_student_description_and_more'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraclass',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extraclass',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.section'),
            preserve_default=False,
        ),
    ]
