# Generated by Django 5.0.6 on 2024-05-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_extraclass_section_extraclass_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraclass',
            name='day',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateField(max_length=10),
        ),
    ]
