# Generated by Django 5.0.6 on 2024-05-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
