# Generated by Django 5.0.6 on 2024-05-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_extraclass_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='day',
            new_name='dayOfWeek',
        ),
    ]
