# Generated by Django 5.0.6 on 2024-05-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_rename_day_timetable_dayofweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='dayOfWeek',
            new_name='day',
        ),
    ]
