# Generated by Django 5.0.6 on 2024-05-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_student_student_description_and_more'),
        ('college', '0008_rename_dayofweek_timetable_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.timetable')),
            ],
        ),
    ]
