# Generated by Django 5.0.6 on 2024-05-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_student_student_description_and_more'),
        ('college', '0009_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='timetable',
        ),
        migrations.AddField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.course'),
            preserve_default=False,
        ),
    ]
