# Generated by Django 5.0.6 on 2024-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
